name: ms_pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - pip
  - pandas>=1.3.0
  - numpy>=1.21.0
  - scipy>=1.7.0
  - scikit-learn>=0.24.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - pyarrow>=6.0.0
  - tqdm>=4.62.0
  - pytest>=6.2.0
  - jupyter>=1.0.0
  - plotly>=5.3.0
  - dask>=2024.1.0
  - dask-expr
  - distributed>=2024.1.0
  - h5py
  - hdf5plugin
  - pymzml
  - pytables
  - snakemake<8
  - statsmodels
  - tabula-py
  - kaleido
  - pip:
    - git+https://github.com/pnnl/deimos.git